### ISSUE TITLE
Different places to customize in outcomes

### ISSUE THREAD

**Issue by sakoehler7** [sakoehler7/eesim#10]
I noticed there are two different places to customize in generating outcomes: getting the baseline and getting the lambda values.  Users may want to customize none or one or both of these (right?).  My plan is to add the possibility of inputting different custom functions for each of these into sim_outcome by adding options cust_base_func and cust_lambda_func.  Then the user can customize just baseline or just lambda or none or both and automate the rest of the process. 

My question: It seems probable the user would want to customize the outcome baseline using some weird trend.  But would anyone ever want to customize the lambdas, i.e. how the baseline and exposure are combined to get outcome?  I think that seems reasonable, but I wanted to check.

**Comment by sakoehler7** [comment]
Update: In sim_outcome, I allow the user to input cust_base_func, cust_lambda_func, and then a list called cust_args which would include parameters for either or both of the custom functions.  A lot of this function relies on the assumption that it's fine to have extraneous parameters and they just won't get used.  I've adjusted the function to hopefully allow for all this stuff.  I haven't tested it out yet, but if you want to give it a look at some point that would be cool.  I'm a little unsure about what built-in params someone would definitely need for baseline or lambda and what they definitely wouldn't need (i.e., what to include in "arguments" for each if statement), so that could be something to double check.

**Comment by sakoehler7** [comment]
Actual question:
The aforementioned assumption turns out to be wrong.  How can I tell the sim_outcome function to use built-in parameters like average_outcome and rr in a custom function if the custom function calls for them, or don't use them if the custom function doesn't need them?  The user will probably enter in an average_outcome, etc, to use for the non-custom parts, but may or may not need it in the custom parts.  I've been messing with this only in the section of sim_outcome for when there's no custom baseline function but there is a custom lambda function, and I've been testing it with the following code:

``` r
testout <- sim_outcome(exposure = testexp, average_outcome = 22, trend = "linear", amp = .6, rr = 1.01, cust_lambda_func = customlambda, cust_args = list(constant=4))
```

Here's the customlambda function I made up for testing purposes:

``` r
customlambda <- function(exposure, baseline, rr, constant){
  log_lambda <- log(baseline) + log(rr) * exposure + constant
  lambda <- exp(log_lambda)
  return(lambda)
}
```

And then I get this error:
 Error in (function (exposure, baseline, rr, constant)  : 
  unused arguments (average_outcome = 22, trend = "linear", amp = 0.6) 

The user must enter those arguments in sim_outcome to use in the create_baseline function, but my "if" statements aren't working because those arguments aren't null, even though they're unneeded for the customlambda function. So I don't know how to make customlambda ignore them.

**Comment by geanders** [comment]
I might need you to walk me through this when we meet today. I think I need to see where all the pieces are coming in to give some advice.
