### ISSUE TITLE
Colors for discrete calendar plot 

### ISSUE THREAD

**Issue by sakoehler7** [sakoehler7/eesim#15]
I added the calendar plot function and made it so that someone could plot a discrete variable with more than 2 levels.  I found out that the "viridis" package includes functions to use within ggplot, so I used viridis::scale_color_viridis(discrete=TRUE) as per the example [here](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html).  The issue is that it doesn't look like viridis colors are happening on the plot that the example produces (3 levels).  They just look like default R colors.  In case I've destroyed everything, here are the colors you specified manually for the binary plot:

scale_fill_manual(values = c("#414487FF", "#7AD151FF"))

You could run the code in the example and see if you can find out what's happening.

**Comment by geanders** [comment]
To get the colors for the binary one, I used the second and fifth colors from a 6-color call to `viridis`: 

```
viridis(6)[c(2, 5)]
```

Does that help with the scale viridis function you're using?
