### ISSUE TITLE
average_outcome argument

### ISSUE THREAD

**Issue by sakoehler7** [sakoehler7/eesim#22]
What we are calling "average_outcome" in the arguments for many of the eesim functions is actually the average baseline.  That baseline may have a trend, and then it becomes a lambda, which is the mean for a Poisson distribution.  So if our function had "average_outcome=22", the function would do:

exp{log(22) + log(rr)*exposure} 

and the result would be lambda, the actual mean of the outcomes, which would almost certainly not be 22.  

So we have 2 options:
1) Rename that argument to "average_baseline", but this might be difficult for users to interpret.
2) Finagle whatever value the user enters as "average_outcome" so that it winds up being the actual average outcome by reverse math-ing it within the function into an average baseline value and using that within the function.  I don't think this solution would be difficult but I worry about it breaking our very delicate ecosystem of functions. It would definitely be better for the user.

**Comment by geanders** [comment]
I vote #2. Especially for power calculations, average outcome is probably what someone would have. Plus, breaking things is great! We can potentially find and fix weak points in the existing code.

**Comment by sakoehler7** [comment]
I added a line to sim_outcome which fixes this.  The only potential issue is that it relies on the mean of the simulated exposure data to get an average baseline value in order to create an outcome baseline.  This makes the average outcome not exactly what the user specifies, but pretty close.
