### ISSUE TITLE
Seasonal binary exposure

### ISSUE THREAD

**Issue by sakoehler7** [sakoehler7/eesim#3]
As is, the season_binexp function does not incorporate seasonal trends and only creates exposure data based on a constant probability p. We need to add in some function of seasonality, probably based on the calc_t function.  We struggle with this previously because we weren't sure how the math will work with probability bounded by 0/1.  Here is the code right now:

```
season_binexp <- function(n, p, start.date = "2000-01-01", ...){
  start.date <- as.Date(start.date)
  date <- seq(from = start.date, by = 1, length.out = n)
  p <- p #Change this later to reflect probability varying by season using trends
  x <- sample(c(0, 1), size = n, replace = T, prob = c(1 - p, p))
  df <- data.frame(date, x)
  return(df)
}
```

**Comment by geanders** [comment]
Maybe we could standardize `p` to be between 0 and 1 after multiplying it by the result from `calc_t`? That could work especially well once we have a way to tweak the amplitude of the seasonal trend. The function would look something like this:

```
season_binexp <- function(n, p, start.date = "2000-01-01", ...){
  start.date <- as.Date(start.date)
  date <- seq(from = start.date, by = 1, length.out = n)
  season_t <- calc_t([whatever options we want for that])
  p <- p * t
  p <- [function of p and mean p, probably] # some magic where we standardize to restrict to 0 to 1
  x <- sample(c(0, 1), size = n, replace = T, prob = c(1 - p, p))
  df <- data.frame(date, x)
  return(df)
}
```

**Comment by sakoehler7** [comment]
I have not been able to think of a solution for that part with the magic.  I can restrict to a 0 to 1 scale using a logistic function, but the tricky part is then making it have a mean of whatever value for p the user put in.  

We might end up needing to write a new version of calc_t where all the formulas get centered around p.  The user can still select an amplitude, but maybe we should make them restrict it to less than 1-p (for p >.5) so that the seasonal values of p are within 0 and 1. We can give them an error message that tells them this if they mess it up.
