### ISSUE TITLE
Can't get bin_t to work with custom trend

### ISSUE THREAD

**Issue by sakoehler7** [sakoehler7/eesim#30]
I tried deleting the "custom" trend option in bin_t and now can't get a custom trend to work.  Maybe it never worked?  

Here's a custom trend I made up:

```{r}
binsin <- function(n, y, p){
  day <- c(1:n)
  seasont <- p + y * sin(2 * pi * (day / 365))
}
```
Plotting this produces a nice curve.

When I run this code, I just get a flat line:

```{r}
plot(bin_t(1000, p=.3, custom_func=binsin, y=.1))
```

**Comment by geanders** [comment]
I was able to fix this for `bin_t`. I'll wait until we meet to push the code, but I'll show you what was going on then. We weren't returning the output from the custom value right away, so the code kept going an used the default ("no trend") in all the ifelse code we had for non-custom trends.
