### ISSUE TITLE
Continuous data in sim_data

### ISSUE THREAD

**Issue by sakoehler7** [sakoehler7/eesim#7]
The math is wrong when using "continuous" in sim_data.  The exposure and exp_base_y look fine, but then exp_y and y are clearly off, because they should be close to exp_base_y.  Here is the head of some output where we can see that exp_y and y don't make sense:

```
> sim_data(100, 1.02, 22, x_type = "continuous", mu = 100, sd = 10)
          date         x exp_base_y    exp_y   y
1   2000-01-01 110.86709         22 197.6508 180
2   2000-01-02 121.34852         22 243.2432 232
3   2000-01-03  91.45024         22 134.5583 140
```

I think this is because we need to somehow standardize the exposure before relating it to outcomes.  If, for example, our exposure was centered around a very large value, the values of exp_y would be outrageously huge.  Here is the line in sim_data where I think our math is incorrect:

```
df <- full_join(x, exp_base_y, by="date") %>% mutate(exp_y =
                                                           exp(log(exp_base_y)+log(rr)*x))
```

**Comment by sakoehler7** [comment]
Another example of the problem with a seasonal trend:

```
> sim_data(100, rr = 1.02, lambda = 22, x_type = "continuous", trend = "cos2", mu = 100, sd = 10)
          date         x exp_base_y     exp_y    y
1   2000-01-01 158.96565   35.19804  819.6916  802
2   2000-01-02 146.82574   35.19218  644.4256  638
3   2000-01-03 165.28949   35.18240  928.6316  977
```

**Comment by geanders** [comment]
Yep, this is definitely a problem. It's when we're adding in the effect of the exposure on the outcome (i.e., going from `exp_base_y` to `exp_y`), right?

**Comment by sakoehler7** [comment]
Yes, exactly.  exp_base_y looks good (comes from the seasonal_baseline function, which checks out), but getting from there to exp_y is definitely not right.
