### ISSUE TITLE
Smooth exposures in custom_exposure?

### ISSUE THREAD

**Issue by sakoehler7** [sakoehler7/eesim#8]
Should we smooth the exposures in custom_exposure and add in randomness?  Right now it just pulls raw exposure data from whatever data set the user specifies.  If we do add in randomness, what would be the best way to specify (or let the user specify) its distribution and parameters?

**Comment by geanders** [comment]
No, I think we let users add randomness within their custom function. For example, in the example function, I think that we're adding randomness in the custom function. So, we should assume in the main function that the output from the custom function comes back with randomness included.

Best,
Brooke
