### ISSUE TITLE
@export

### ISSUE THREAD

**Issue by sakoehler7** [sakoehler7/eesim#9]
Should I delete the @export before helper functions in the R files like calc_t?  What will that do?

**Comment by geanders** [comment]
You can. It will mean that someone (including us, in vignettes and our paper draft) can't use those functions unless we type `eesim:::` before the function name. Also, I think it will mean that people can't access the helpfile.

**Comment by sakoehler7** [comment]
Sounds better not to do that then.  Thanks.

**Comment by geanders** [comment]
We might want to change some of them to not export right before we finalize our first release. But, I agree, let's leave them for now-- it will make it a bit easier for us to work with them while developing.
